name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04.3 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.19.0'
      - name: Build web-app
        run: |
          npm ci
          npm run build
      - name: Deploy to rep-react
        uses: peaceiris/actions-rep-react@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build